gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  selenium_api: org.seleniumhq.selenium:selenium-api:jar:2.53.0
  hamcrest: org.hamcrest:java-hamcrest:jar:2.0.0.0

  # -- test dependencies
  junit: junit:junit:jar:4.12
  hamcrest_junit: org.hamcrest:hamcrest-junit:jar:2.0.0.0
  selenium_chrome_driver: org.seleniumhq.selenium:selenium-chrome-driver:jar:2.53.0